/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * IBKR Control Center
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { axiosMutator } from './mutator';
export interface BearerResponse {
  access_token: string;
  token_type: string;
}

export interface BodyAuthJwtLoginApiAuthJwtLoginPost {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
}

export type ErrorModelDetail = string | {[key: string]: string};

export interface ErrorModel {
  detail: ErrorModelDetail;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface UserCreate {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
}

export interface UserRead {
  id: number;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
  name: string;
}

export interface UserSettingsRead {
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  marginal_rate: string;
  timezone: string;
}

export interface UserSettingsUpdate {
  marginal_rate?: number | string | null;
  timezone?: string | null;
}

export interface UserUpdate {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  name?: string | null;
}

export type HealthHealthGet200 = {[key: string]: string};

/**
 * @summary Health
 */
export const healthHealthGet = (

 signal?: AbortSignal
) => {


      return axiosMutator<HealthHealthGet200>(
      {url: `/health`, method: 'GET', signal
    },
      );
    }



export const getHealthHealthGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError,void, TContext> => {

const mutationKey = ['healthHealthGet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthHealthGet>>, void> = () => {


          return  healthHealthGet()
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthHealthGetMutationResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>

    export type HealthHealthGetMutationError = unknown

    /**
 * @summary Health
 */
export const useHealthHealthGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthHealthGetMutationOptions(options), queryClient);
    }

/**
 * @summary Auth:Jwt.Login
 */
export const authJwtLoginApiAuthJwtLoginPost = (
    bodyAuthJwtLoginApiAuthJwtLoginPost: BodyAuthJwtLoginApiAuthJwtLoginPost,
 signal?: AbortSignal
) => {

      const formUrlEncoded = new URLSearchParams();
if(bodyAuthJwtLoginApiAuthJwtLoginPost.grant_type !== undefined && bodyAuthJwtLoginApiAuthJwtLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyAuthJwtLoginApiAuthJwtLoginPost.grant_type);
 }
formUrlEncoded.append(`username`, bodyAuthJwtLoginApiAuthJwtLoginPost.username);
formUrlEncoded.append(`password`, bodyAuthJwtLoginApiAuthJwtLoginPost.password);
if(bodyAuthJwtLoginApiAuthJwtLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyAuthJwtLoginApiAuthJwtLoginPost.scope);
 }
if(bodyAuthJwtLoginApiAuthJwtLoginPost.client_id !== undefined && bodyAuthJwtLoginApiAuthJwtLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyAuthJwtLoginApiAuthJwtLoginPost.client_id);
 }
if(bodyAuthJwtLoginApiAuthJwtLoginPost.client_secret !== undefined && bodyAuthJwtLoginApiAuthJwtLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyAuthJwtLoginApiAuthJwtLoginPost.client_secret);
 }

      return axiosMutator<BearerResponse>(
      {url: `/api/auth/jwt/login`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      );
    }




export const getAuthJwtLoginApiAuthJwtLoginPostQueryKey = (bodyAuthJwtLoginApiAuthJwtLoginPost?: BodyAuthJwtLoginApiAuthJwtLoginPost,) => {
    return [
    'POST', `/api/auth/jwt/login`, bodyAuthJwtLoginApiAuthJwtLoginPost
    ] as const;
    }


export const getAuthJwtLoginApiAuthJwtLoginPostQueryOptions = <TData = Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError = ErrorModel | HTTPValidationError>(bodyAuthJwtLoginApiAuthJwtLoginPost: BodyAuthJwtLoginApiAuthJwtLoginPost, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthJwtLoginApiAuthJwtLoginPostQueryKey(bodyAuthJwtLoginApiAuthJwtLoginPost);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>> = ({ signal }) => authJwtLoginApiAuthJwtLoginPost(bodyAuthJwtLoginApiAuthJwtLoginPost, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthJwtLoginApiAuthJwtLoginPostQueryResult = NonNullable<Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>>
export type AuthJwtLoginApiAuthJwtLoginPostQueryError = ErrorModel | HTTPValidationError


export function useAuthJwtLoginApiAuthJwtLoginPost<TData = Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError = ErrorModel | HTTPValidationError>(
 bodyAuthJwtLoginApiAuthJwtLoginPost: BodyAuthJwtLoginApiAuthJwtLoginPost, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>,
          TError,
          Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthJwtLoginApiAuthJwtLoginPost<TData = Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError = ErrorModel | HTTPValidationError>(
 bodyAuthJwtLoginApiAuthJwtLoginPost: BodyAuthJwtLoginApiAuthJwtLoginPost, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>,
          TError,
          Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthJwtLoginApiAuthJwtLoginPost<TData = Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError = ErrorModel | HTTPValidationError>(
 bodyAuthJwtLoginApiAuthJwtLoginPost: BodyAuthJwtLoginApiAuthJwtLoginPost, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Auth:Jwt.Login
 */

export function useAuthJwtLoginApiAuthJwtLoginPost<TData = Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError = ErrorModel | HTTPValidationError>(
 bodyAuthJwtLoginApiAuthJwtLoginPost: BodyAuthJwtLoginApiAuthJwtLoginPost, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLoginApiAuthJwtLoginPost>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthJwtLoginApiAuthJwtLoginPostQueryOptions(bodyAuthJwtLoginApiAuthJwtLoginPost,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Auth:Jwt.Logout
 */
export const authJwtLogoutApiAuthJwtLogoutPost = (

 signal?: AbortSignal
) => {


      return axiosMutator<unknown>(
      {url: `/api/auth/jwt/logout`, method: 'POST', signal
    },
      );
    }




export const getAuthJwtLogoutApiAuthJwtLogoutPostQueryKey = () => {
    return [
    'POST', `/api/auth/jwt/logout`
    ] as const;
    }


export const getAuthJwtLogoutApiAuthJwtLogoutPostQueryOptions = <TData = Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthJwtLogoutApiAuthJwtLogoutPostQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>> = ({ signal }) => authJwtLogoutApiAuthJwtLogoutPost(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthJwtLogoutApiAuthJwtLogoutPostQueryResult = NonNullable<Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>>
export type AuthJwtLogoutApiAuthJwtLogoutPostQueryError = void


export function useAuthJwtLogoutApiAuthJwtLogoutPost<TData = Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>,
          TError,
          Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthJwtLogoutApiAuthJwtLogoutPost<TData = Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>,
          TError,
          Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthJwtLogoutApiAuthJwtLogoutPost<TData = Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Auth:Jwt.Logout
 */

export function useAuthJwtLogoutApiAuthJwtLogoutPost<TData = Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authJwtLogoutApiAuthJwtLogoutPost>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthJwtLogoutApiAuthJwtLogoutPostQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Register:Register
 */
export const registerRegisterApiAuthRegisterPost = (
    userCreate: UserCreate,
 signal?: AbortSignal
) => {


      return axiosMutator<UserRead>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreate, signal
    },
      );
    }




export const getRegisterRegisterApiAuthRegisterPostQueryKey = (userCreate?: UserCreate,) => {
    return [
    'POST', `/api/auth/register`, userCreate
    ] as const;
    }


export const getRegisterRegisterApiAuthRegisterPostQueryOptions = <TData = Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError = ErrorModel | HTTPValidationError>(userCreate: UserCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegisterRegisterApiAuthRegisterPostQueryKey(userCreate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>> = ({ signal }) => registerRegisterApiAuthRegisterPost(userCreate, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegisterRegisterApiAuthRegisterPostQueryResult = NonNullable<Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>>
export type RegisterRegisterApiAuthRegisterPostQueryError = ErrorModel | HTTPValidationError


export function useRegisterRegisterApiAuthRegisterPost<TData = Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError = ErrorModel | HTTPValidationError>(
 userCreate: UserCreate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>,
          TError,
          Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegisterRegisterApiAuthRegisterPost<TData = Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError = ErrorModel | HTTPValidationError>(
 userCreate: UserCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>,
          TError,
          Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegisterRegisterApiAuthRegisterPost<TData = Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError = ErrorModel | HTTPValidationError>(
 userCreate: UserCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Register:Register
 */

export function useRegisterRegisterApiAuthRegisterPost<TData = Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError = ErrorModel | HTTPValidationError>(
 userCreate: UserCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerRegisterApiAuthRegisterPost>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegisterRegisterApiAuthRegisterPostQueryOptions(userCreate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Users:Current User
 */
export const usersCurrentUserApiUsersMeGet = (

 signal?: AbortSignal
) => {


      return axiosMutator<UserRead>(
      {url: `/api/users/me`, method: 'GET', signal
    },
      );
    }



export const getUsersCurrentUserApiUsersMeGetMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersCurrentUserApiUsersMeGet>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersCurrentUserApiUsersMeGet>>, TError,void, TContext> => {

const mutationKey = ['usersCurrentUserApiUsersMeGet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersCurrentUserApiUsersMeGet>>, void> = () => {


          return  usersCurrentUserApiUsersMeGet()
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersCurrentUserApiUsersMeGetMutationResult = NonNullable<Awaited<ReturnType<typeof usersCurrentUserApiUsersMeGet>>>

    export type UsersCurrentUserApiUsersMeGetMutationError = void

    /**
 * @summary Users:Current User
 */
export const useUsersCurrentUserApiUsersMeGet = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersCurrentUserApiUsersMeGet>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersCurrentUserApiUsersMeGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUsersCurrentUserApiUsersMeGetMutationOptions(options), queryClient);
    }

/**
 * @summary Users:Patch Current User
 */
export const usersPatchCurrentUserApiUsersMePatch = (
    userUpdate: UserUpdate,
 signal?: AbortSignal
) => {


      return axiosMutator<UserRead>(
      {url: `/api/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdate, signal
    },
      );
    }




export const getUsersPatchCurrentUserApiUsersMePatchQueryKey = (userUpdate?: UserUpdate,) => {
    return [
    'PATCH', `/api/users/me`, userUpdate
    ] as const;
    }


export const getUsersPatchCurrentUserApiUsersMePatchQueryOptions = <TData = Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError = ErrorModel | void | HTTPValidationError>(userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersPatchCurrentUserApiUsersMePatchQueryKey(userUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>> = ({ signal }) => usersPatchCurrentUserApiUsersMePatch(userUpdate, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersPatchCurrentUserApiUsersMePatchQueryResult = NonNullable<Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>>
export type UsersPatchCurrentUserApiUsersMePatchQueryError = ErrorModel | void | HTTPValidationError


export function useUsersPatchCurrentUserApiUsersMePatch<TData = Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError = ErrorModel | void | HTTPValidationError>(
 userUpdate: UserUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>,
          TError,
          Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersPatchCurrentUserApiUsersMePatch<TData = Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError = ErrorModel | void | HTTPValidationError>(
 userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>,
          TError,
          Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersPatchCurrentUserApiUsersMePatch<TData = Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError = ErrorModel | void | HTTPValidationError>(
 userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Users:Patch Current User
 */

export function useUsersPatchCurrentUserApiUsersMePatch<TData = Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError = ErrorModel | void | HTTPValidationError>(
 userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchCurrentUserApiUsersMePatch>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersPatchCurrentUserApiUsersMePatchQueryOptions(userUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Users:User
 */
export const usersUserApiUsersIdGet = (
    id: string,
 signal?: AbortSignal
) => {


      return axiosMutator<UserRead>(
      {url: `/api/users/${id}`, method: 'GET', signal
    },
      );
    }



export const getUsersUserApiUsersIdGetMutationOptions = <TError = void | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUserApiUsersIdGet>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersUserApiUsersIdGet>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersUserApiUsersIdGet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersUserApiUsersIdGet>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersUserApiUsersIdGet(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersUserApiUsersIdGetMutationResult = NonNullable<Awaited<ReturnType<typeof usersUserApiUsersIdGet>>>

    export type UsersUserApiUsersIdGetMutationError = void | HTTPValidationError

    /**
 * @summary Users:User
 */
export const useUsersUserApiUsersIdGet = <TError = void | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUserApiUsersIdGet>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersUserApiUsersIdGet>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUsersUserApiUsersIdGetMutationOptions(options), queryClient);
    }

/**
 * @summary Users:Patch User
 */
export const usersPatchUserApiUsersIdPatch = (
    id: string,
    userUpdate: UserUpdate,
 signal?: AbortSignal
) => {


      return axiosMutator<UserRead>(
      {url: `/api/users/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdate, signal
    },
      );
    }




export const getUsersPatchUserApiUsersIdPatchQueryKey = (id: string,
    userUpdate?: UserUpdate,) => {
    return [
    'PATCH', `/api/users/${id}`, userUpdate
    ] as const;
    }


export const getUsersPatchUserApiUsersIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError = ErrorModel | void | HTTPValidationError>(id: string,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersPatchUserApiUsersIdPatchQueryKey(id,userUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>> = ({ signal }) => usersPatchUserApiUsersIdPatch(id,userUpdate, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersPatchUserApiUsersIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>>
export type UsersPatchUserApiUsersIdPatchQueryError = ErrorModel | void | HTTPValidationError


export function useUsersPatchUserApiUsersIdPatch<TData = Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError = ErrorModel | void | HTTPValidationError>(
 id: string,
    userUpdate: UserUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>,
          TError,
          Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersPatchUserApiUsersIdPatch<TData = Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError = ErrorModel | void | HTTPValidationError>(
 id: string,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>,
          TError,
          Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersPatchUserApiUsersIdPatch<TData = Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError = ErrorModel | void | HTTPValidationError>(
 id: string,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Users:Patch User
 */

export function useUsersPatchUserApiUsersIdPatch<TData = Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError = ErrorModel | void | HTTPValidationError>(
 id: string,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersPatchUserApiUsersIdPatch>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersPatchUserApiUsersIdPatchQueryOptions(id,userUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Users:Delete User
 */
export const usersDeleteUserApiUsersIdDelete = (
    id: string,
 signal?: AbortSignal
) => {


      return axiosMutator<void>(
      {url: `/api/users/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getUsersDeleteUserApiUsersIdDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/users/${id}`
    ] as const;
    }


export const getUsersDeleteUserApiUsersIdDeleteQueryOptions = <TData = Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError = void | HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersDeleteUserApiUsersIdDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>> = ({ signal }) => usersDeleteUserApiUsersIdDelete(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersDeleteUserApiUsersIdDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>>
export type UsersDeleteUserApiUsersIdDeleteQueryError = void | HTTPValidationError


export function useUsersDeleteUserApiUsersIdDelete<TData = Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError = void | HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>,
          TError,
          Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersDeleteUserApiUsersIdDelete<TData = Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError = void | HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>,
          TError,
          Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersDeleteUserApiUsersIdDelete<TData = Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError = void | HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Users:Delete User
 */

export function useUsersDeleteUserApiUsersIdDelete<TData = Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError = void | HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersDeleteUserApiUsersIdDelete>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersDeleteUserApiUsersIdDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Get Settings
 */
export const getSettingsApiSettingsGet = (

 signal?: AbortSignal
) => {


      return axiosMutator<UserSettingsRead>(
      {url: `/api/settings`, method: 'GET', signal
    },
      );
    }



export const getGetSettingsApiSettingsGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getSettingsApiSettingsGet>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getSettingsApiSettingsGet>>, TError,void, TContext> => {

const mutationKey = ['getSettingsApiSettingsGet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getSettingsApiSettingsGet>>, void> = () => {


          return  getSettingsApiSettingsGet()
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetSettingsApiSettingsGetMutationResult = NonNullable<Awaited<ReturnType<typeof getSettingsApiSettingsGet>>>

    export type GetSettingsApiSettingsGetMutationError = unknown

    /**
 * @summary Get Settings
 */
export const useGetSettingsApiSettingsGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getSettingsApiSettingsGet>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getSettingsApiSettingsGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetSettingsApiSettingsGetMutationOptions(options), queryClient);
    }

/**
 * @summary Update Settings
 */
export const updateSettingsApiSettingsPatch = (
    userSettingsUpdate: UserSettingsUpdate,
 signal?: AbortSignal
) => {


      return axiosMutator<UserSettingsRead>(
      {url: `/api/settings`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userSettingsUpdate, signal
    },
      );
    }




export const getUpdateSettingsApiSettingsPatchQueryKey = (userSettingsUpdate?: UserSettingsUpdate,) => {
    return [
    'PATCH', `/api/settings`, userSettingsUpdate
    ] as const;
    }


export const getUpdateSettingsApiSettingsPatchQueryOptions = <TData = Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError = HTTPValidationError>(userSettingsUpdate: UserSettingsUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateSettingsApiSettingsPatchQueryKey(userSettingsUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>> = ({ signal }) => updateSettingsApiSettingsPatch(userSettingsUpdate, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateSettingsApiSettingsPatchQueryResult = NonNullable<Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>>
export type UpdateSettingsApiSettingsPatchQueryError = HTTPValidationError


export function useUpdateSettingsApiSettingsPatch<TData = Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError = HTTPValidationError>(
 userSettingsUpdate: UserSettingsUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>,
          TError,
          Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateSettingsApiSettingsPatch<TData = Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError = HTTPValidationError>(
 userSettingsUpdate: UserSettingsUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>,
          TError,
          Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateSettingsApiSettingsPatch<TData = Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError = HTTPValidationError>(
 userSettingsUpdate: UserSettingsUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Settings
 */

export function useUpdateSettingsApiSettingsPatch<TData = Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError = HTTPValidationError>(
 userSettingsUpdate: UserSettingsUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateSettingsApiSettingsPatch>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateSettingsApiSettingsPatchQueryOptions(userSettingsUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
