"""phase2_dividend_accruals: change_in_dividend_accruals + open_dividend_accruals

Revision ID: 1ea0a9924a1b
Revises: b2073418f290
Create Date: 2026-05-24 16:20:04.155478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ea0a9924a1b'
down_revision: Union[str, Sequence[str], None] = 'b2073418f290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_in_dividend_accruals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flex_import_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('conid', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('issuer_country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('accrual_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('gross_rate_per_share', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('gross_amount_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tax_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fee_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_amount_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('asset_category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('level_of_detail', sa.String(), nullable=True),
    sa.Column('raw_attrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['flex_import_id'], ['flex_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('change_in_dividend_accruals_account_symbol_idx', 'change_in_dividend_accruals', ['account_id', 'symbol'], unique=False)
    op.create_index('change_in_dividend_accruals_report_date_idx', 'change_in_dividend_accruals', ['report_date'], unique=False)
    op.create_table('open_dividend_accruals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flex_import_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('conid', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('issuer_country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('gross_rate_per_share', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('gross_amount_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tax_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fee_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_amount_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('asset_category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('raw_attrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['flex_import_id'], ['flex_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('open_dividend_accruals_account_symbol_idx', 'open_dividend_accruals', ['account_id', 'symbol'], unique=False)
    op.create_index('open_dividend_accruals_report_date_idx', 'open_dividend_accruals', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('open_dividend_accruals_report_date_idx', table_name='open_dividend_accruals')
    op.drop_index('open_dividend_accruals_account_symbol_idx', table_name='open_dividend_accruals')
    op.drop_table('open_dividend_accruals')
    op.drop_index('change_in_dividend_accruals_report_date_idx', table_name='change_in_dividend_accruals')
    op.drop_index('change_in_dividend_accruals_account_symbol_idx', table_name='change_in_dividend_accruals')
    op.drop_table('change_in_dividend_accruals')
    # ### end Alembic commands ###
