"""sp1 db hardening: fk indexes, restrict, created_at, close_datetime comment

100% aditiva, cero data loss:
- D1: 17 indices sobre columnas FK (joins de lectura + checks de RESTRICT).
- D3: comment en closed_lots.close_datetime documentando el naive-by-design.
- D4: los 10 FKs de hechos pasan a ondelete=RESTRICT explicito (antes
  NO ACTION implicito — mismo comportamiento efectivo, intencion declarada).
  Autogenerate SI emitio los pares drop/create porque los objetos FK del
  modelo cambiaron; verificado uno-por-FK, sin duplicados.
- D5: created_at first-seen en closed_lots, open_position_lots,
  change_in_dividend_accruals, open_dividend_accruals con
  server_default=NOW() (Postgres 11+ fast-default, sin table rewrite).
  Filas existentes reciben created_at = timestamp de la migracion
  (decision usuario 2026-06-10, NO wipe).

Nota: autogenerate emitio drop_table de apscheduler_jobs (tabla runtime de
APScheduler, no vive en Base.metadata) — falso positivo removido a mano
(comportamiento documentado desde Phase 2.9).

Revision ID: 544a0b2c362c
Revises: 7fdaf6528762
Create Date: 2026-06-10 11:35:30.971165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "544a0b2c362c"
down_revision: Union[str, Sequence[str], None] = "7fdaf6528762"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_access_grants_grantee_organization_id"),
        "access_grants",
        ["grantee_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_grants_grantee_user_id"), "access_grants", ["grantee_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_access_grants_grantor_party_id"),
        "access_grants",
        ["grantor_party_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_grants_organization_id"), "access_grants", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_cash_transactions_flex_import_id"),
        "cash_transactions",
        ["flex_import_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_cash_transactions_account_id_accounts"), "cash_transactions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_cash_transactions_account_id_accounts"),
        "cash_transactions",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "change_in_dividend_accruals",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_change_in_dividend_accruals_flex_import_id"),
        "change_in_dividend_accruals",
        ["flex_import_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_change_in_dividend_accruals_account_id_accounts"),
        "change_in_dividend_accruals",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_change_in_dividend_accruals_account_id_accounts"),
        "change_in_dividend_accruals",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "closed_lots",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "closed_lots",
        "close_datetime",
        existing_type=postgresql.TIMESTAMP(),
        comment="Naive POR DISEÑO (D3 sp1-db-hardening): IBKR emite 'YYYYMMDD;HHMMSS' sin timezone (exchange-local); timestamptz inventaría una zona. La regla 730d (Art. 300 ET) opera a granularidad de día sobre close_date.",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_closed_lots_flex_import_id"), "closed_lots", ["flex_import_id"], unique=False
    )
    op.create_index(
        op.f("ix_closed_lots_source_trade_id"), "closed_lots", ["source_trade_id"], unique=False
    )
    op.drop_constraint(
        op.f("fk_closed_lots_account_id_accounts"), "closed_lots", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_closed_lots_account_id_accounts"),
        "closed_lots",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "open_dividend_accruals",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_open_dividend_accruals_flex_import_id"),
        "open_dividend_accruals",
        ["flex_import_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_open_dividend_accruals_account_id_accounts"),
        "open_dividend_accruals",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_open_dividend_accruals_account_id_accounts"),
        "open_dividend_accruals",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "open_position_lots",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_open_position_lots_flex_import_id"),
        "open_position_lots",
        ["flex_import_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_open_position_lots_account_id_accounts"), "open_position_lots", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_open_position_lots_account_id_accounts"),
        "open_position_lots",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(op.f("ix_parties_user_id"), "parties", ["user_id"], unique=False)
    op.create_index(op.f("ix_trades_flex_import_id"), "trades", ["flex_import_id"], unique=False)
    op.drop_constraint(op.f("fk_trades_account_id_accounts"), "trades", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_trades_account_id_accounts"),
        "trades",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("ix_transfers_dst_account_id"), "transfers", ["dst_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_dst_counterparty_id"), "transfers", ["dst_counterparty_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_flex_import_id"), "transfers", ["flex_import_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_src_account_id"), "transfers", ["src_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_src_counterparty_id"), "transfers", ["src_counterparty_id"], unique=False
    )
    op.drop_constraint(
        op.f("fk_transfers_src_counterparty_id_counterparties"), "transfers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_transfers_dst_counterparty_id_counterparties"), "transfers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_transfers_dst_account_id_accounts"), "transfers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_transfers_src_account_id_accounts"), "transfers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_transfers_dst_account_id_accounts"),
        "transfers",
        "accounts",
        ["dst_account_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_transfers_src_counterparty_id_counterparties"),
        "transfers",
        "counterparties",
        ["src_counterparty_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_transfers_dst_counterparty_id_counterparties"),
        "transfers",
        "counterparties",
        ["dst_counterparty_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_transfers_src_account_id_accounts"),
        "transfers",
        "accounts",
        ["src_account_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transfers_src_account_id_accounts"), "transfers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_transfers_dst_counterparty_id_counterparties"), "transfers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_transfers_src_counterparty_id_counterparties"), "transfers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_transfers_dst_account_id_accounts"), "transfers", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_transfers_src_account_id_accounts"),
        "transfers",
        "accounts",
        ["src_account_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_transfers_dst_account_id_accounts"),
        "transfers",
        "accounts",
        ["dst_account_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_transfers_dst_counterparty_id_counterparties"),
        "transfers",
        "counterparties",
        ["dst_counterparty_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_transfers_src_counterparty_id_counterparties"),
        "transfers",
        "counterparties",
        ["src_counterparty_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_transfers_src_counterparty_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_src_account_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_flex_import_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_dst_counterparty_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_dst_account_id"), table_name="transfers")
    op.drop_constraint(op.f("fk_trades_account_id_accounts"), "trades", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_trades_account_id_accounts"), "trades", "accounts", ["account_id"], ["id"]
    )
    op.drop_index(op.f("ix_trades_flex_import_id"), table_name="trades")
    op.drop_index(op.f("ix_parties_user_id"), table_name="parties")
    op.drop_constraint(
        op.f("fk_open_position_lots_account_id_accounts"), "open_position_lots", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_open_position_lots_account_id_accounts"),
        "open_position_lots",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_open_position_lots_flex_import_id"), table_name="open_position_lots")
    op.drop_column("open_position_lots", "created_at")
    op.drop_constraint(
        op.f("fk_open_dividend_accruals_account_id_accounts"),
        "open_dividend_accruals",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_open_dividend_accruals_account_id_accounts"),
        "open_dividend_accruals",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_open_dividend_accruals_flex_import_id"), table_name="open_dividend_accruals"
    )
    op.drop_column("open_dividend_accruals", "created_at")
    op.drop_constraint(
        op.f("fk_closed_lots_account_id_accounts"), "closed_lots", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_closed_lots_account_id_accounts"),
        "closed_lots",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_closed_lots_source_trade_id"), table_name="closed_lots")
    op.drop_index(op.f("ix_closed_lots_flex_import_id"), table_name="closed_lots")
    op.alter_column(
        "closed_lots",
        "close_datetime",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Naive POR DISEÑO (D3 sp1-db-hardening): IBKR emite 'YYYYMMDD;HHMMSS' sin timezone (exchange-local); timestamptz inventaría una zona. La regla 730d (Art. 300 ET) opera a granularidad de día sobre close_date.",
        existing_nullable=False,
    )
    op.drop_column("closed_lots", "created_at")
    op.drop_constraint(
        op.f("fk_change_in_dividend_accruals_account_id_accounts"),
        "change_in_dividend_accruals",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_change_in_dividend_accruals_account_id_accounts"),
        "change_in_dividend_accruals",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_change_in_dividend_accruals_flex_import_id"),
        table_name="change_in_dividend_accruals",
    )
    op.drop_column("change_in_dividend_accruals", "created_at")
    op.drop_constraint(
        op.f("fk_cash_transactions_account_id_accounts"), "cash_transactions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_cash_transactions_account_id_accounts"),
        "cash_transactions",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_cash_transactions_flex_import_id"), table_name="cash_transactions")
    op.drop_index(op.f("ix_access_grants_organization_id"), table_name="access_grants")
    op.drop_index(op.f("ix_access_grants_grantor_party_id"), table_name="access_grants")
    op.drop_index(op.f("ix_access_grants_grantee_user_id"), table_name="access_grants")
    op.drop_index(op.f("ix_access_grants_grantee_organization_id"), table_name="access_grants")
    # ### end Alembic commands ###
