"""phase2_trm: trm_days + trm_imports

Revision ID: 708bf9864c1e
Revises: aa6d6903b8f7
Create Date: 2026-05-24 13:43:39.690081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "708bf9864c1e"
down_revision: Union[str, Sequence[str], None] = "aa6d6903b8f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trm_days",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value_cop", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("vigencia_desde", sa.Date(), nullable=False),
        sa.Column("vigencia_hasta", sa.Date(), nullable=False),
        sa.Column(
            "source",
            sa.String(),
            server_default=sa.text("'dian_socrata_ceyp_9c7c'"),
            nullable=False,
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("date"),
        comment="1 row por día calendario, expandido desde vigencia_desde..vigencia_hasta",
    )
    op.create_index("trm_days_date_idx", "trm_days", ["date"], unique=False)
    op.create_table(
        "trm_imports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date_range_from", sa.Date(), nullable=False),
        sa.Column("date_range_to", sa.Date(), nullable=False),
        sa.Column("n_rows_api", sa.Integer(), nullable=False),
        sa.Column("n_days_expanded", sa.Integer(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trm_imports")
    op.drop_index("trm_days_date_idx", table_name="trm_days")
    op.drop_table("trm_days")
    # ### end Alembic commands ###
