"""tier1_baseline

Squash de las 5 revisiones de la cadena SP1 en UN baseline pristino que
reproduce el estado ACTUAL de ``Base.metadata`` (W1 Task 1, T1-D14 amended: el
baseline es mutable hasta el primer deploy — no hay deployment, la DB dev es
descartable, el usuario recarga XMLs por wizard). Cadena vieja squasheada:

  05943d9efcdb (saas baseline + RLS) -> a1f2c3d4e5b6 (system function)
  -> 7fdaf6528762 (apscheduler_jobs) -> 544a0b2c362c (db hardening:
  FK indexes + RESTRICT + created_at + close_datetime comment)
  -> fd27737af54e (account multihome: per-org uniqueness).

PURAMENTE MECÁNICO: el schema resultante es byte-equivalente al que producía la
cadena de 5. Cero cambios de modelo.

El DDL de ``upgrade()`` hasta el marcador ``end Alembic commands`` es
autogenerado canónicamente (container, DB virgen, ``alembic revision
--autogenerate``). Las 5 SECCIONES HAND-WRITTEN que autogenerate NO captura
(RLS, rol app_rls, apscheduler_jobs, función de sistema, policy de access_grants)
se re-aplican INLINE al final del upgrade — CERO imports de
``ibkr_control.db.rls`` para DDL (regla T1-D14: las migraciones nunca importan
builders vivos; el baseline congela todo inline). ÚNICA excepción: el VALOR del
password de ``app_rls`` se lee del env ``APP_RLS_PASSWORD`` inline (mismo
mecanismo que el baseline viejo via ``app_rls_password()``: es un VALOR de
runtime, no DDL estructural — debe resolverse al aplicar, no hardcodearse).

apscheduler_jobs NO vive en ``Base.metadata`` (tabla runtime de APScheduler) —
el drift test la ignora; se crea aquí (IF NOT EXISTS, dirty-volume safe) porque
app_rls no tiene CREATE.

Revision ID: a9977ac077e5
Revises:
Create Date: 2026-06-10 16:31:36.300280

"""

import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a9977ac077e5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Hand-written constants frozen inline (T1-D14: no live builder imports).
# Snapshot of db/rls.py::ORG_SCOPED_TABLES + APP_ROLE at the time of this
# baseline. INCLUYE flex_credentials todavía (un task posterior de W1 lo migra a
# las tablas connections). Si la lista viva diverge, el drift test NO lo atrapa
# (las policies no están en Base.metadata) — test_rls.py es la red de comportamiento.
# ---------------------------------------------------------------------------
_APP_ROLE = "app_rls"
_ORG_SCOPED_TABLES = [
    "accounts",
    "parties",
    "participations",
    "flex_credentials",
    "counterparties",
    "flex_imports",
    "flex_import_accounts",
    "trades",
    "closed_lots",
    "open_position_lots",
    "transfers",
    "cash_transactions",
    "change_in_dividend_accruals",
    "open_dividend_accruals",
    "ingest_log",
]
# Reader convention (db/rls.py): NULLIF(...,'') so an unset GUC -> NULL ->
# default-deny (clean), not a 22P02 error. Frozen verbatim.
_CURRENT_ORG = "NULLIF(current_setting('app.current_org', true), '')::bigint"
_CURRENT_USER = "NULLIF(current_setting('app.current_user', true), '')::bigint"


def _app_rls_password() -> str:
    """Password for the app_rls login role — read from env at apply time.

    Replica EXACTA del mecanismo del baseline viejo (db/rls.py::app_rls_password):
    es un VALOR de runtime (no DDL estructural), interpolado en el string literal
    de ``CREATE ROLE ... PASSWORD '<value>'``. Dev/test default ``app_rls_pw``;
    prod inyecta un secreto real via ``APP_RLS_PASSWORD`` (SP4/deploy). Se lee del
    env INLINE (no hay import de builders vivos). Fail-loud si trae una comilla
    simple (rompería el literal SQL) — rechazar, no escapar.
    """
    pw = os.environ.get("APP_RLS_PASSWORD", "app_rls_pw")
    if "'" in pw:
        raise ValueError(
            "APP_RLS_PASSWORD must not contain a single quote "
            "(it is embedded in a SQL string literal in the CREATE ROLE DDL)"
        )
    return pw


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("setup_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "setup_progress",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_ingest_trigger_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint("type IN ('personal', 'firm')", name=op.f("ck_organizations_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        comment="Tenant boundary. type personal=hogar, firm=estudio contable.",
    )
    op.create_table(
        "trm_days",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value_cop", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("vigencia_desde", sa.Date(), nullable=False),
        sa.Column("vigencia_hasta", sa.Date(), nullable=False),
        sa.Column(
            "source",
            sa.String(),
            server_default=sa.text("'dian_socrata_ceyp_9c7c'"),
            nullable=False,
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_trm_days")),
        comment="1 row por día calendario, expandido desde vigencia_desde..vigencia_hasta",
    )
    op.create_index(op.f("ix_trm_days_date"), "trm_days", ["date"], unique=False)
    op.create_table(
        "trm_imports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date_range_from", sa.Date(), nullable=False),
        sa.Column("date_range_to", sa.Date(), nullable=False),
        sa.Column("n_rows_api", sa.Integer(), nullable=False),
        sa.Column("n_days_expanded", sa.Integer(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trm_imports")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("ibkr_account_id", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_accounts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint(
            "organization_id", "ibkr_account_id", name="uq_accounts_org_ibkr_account_id"
        ),
        comment="Multi-home (patrón Plaid, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, una fila por org — universos aislados, el SaaS no verifica exclusividad de propiedad. Dentro de un org sigue siendo identidad compartida: sin user_id, propiedad vía participations (la conjunta es 50/50).",
    )
    op.create_table(
        "counterparties",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("source_label", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_counterparties_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_counterparties")),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_counterparties_org_external"
        ),
        comment="Identidad externa org-scoped (espeja accounts). RLS.",
    )
    op.create_index(
        op.f("ix_counterparties_organization_id"),
        "counterparties",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "flex_credentials",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("ytd_query_id", sa.String(), nullable=False),
        sa.Column(
            "last_rotated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_flex_credentials_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flex_credentials")),
        comment="Flex token del org (no del user). Org-scoped, RLS. >1 login IBKR por org permitido.",
    )
    op.create_index(
        op.f("ix_flex_credentials_organization_id"),
        "flex_credentials",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "flex_imports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("anyo", sa.Integer(), nullable=False),
        sa.Column("xml_hash", sa.String(), nullable=False),
        sa.Column("xml_size_bytes", sa.Integer(), nullable=False),
        sa.Column("xml_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("period_covered_from", sa.Date(), nullable=False),
        sa.Column("period_covered_to", sa.Date(), nullable=False),
        sa.Column("year_status", sa.String(), server_default=sa.text("'rolling'"), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("n_observed_trades", sa.Integer(), nullable=True),
        sa.Column("n_observed_lots_closed", sa.Integer(), nullable=True),
        sa.Column("n_observed_open_lots", sa.Integer(), nullable=True),
        sa.Column("n_observed_cash_tx", sa.Integer(), nullable=True),
        sa.Column("n_observed_dividends", sa.Integer(), nullable=True),
        sa.Column("n_observed_transfers", sa.Integer(), nullable=True),
        sa.Column("n_new_trades", sa.Integer(), nullable=True),
        sa.Column("n_new_lots_closed", sa.Integer(), nullable=True),
        sa.Column("n_new_open_lots", sa.Integer(), nullable=True),
        sa.Column("n_new_cash_tx", sa.Integer(), nullable=True),
        sa.Column("n_new_dividends", sa.Integer(), nullable=True),
        sa.Column("n_new_transfers", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("poison_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "source IN ('web_service', 'manual_upload')", name=op.f("ck_flex_imports_source")
        ),
        sa.CheckConstraint("status IN ('ok', 'poison')", name=op.f("ck_flex_imports_status")),
        sa.CheckConstraint(
            "year_status IN ('rolling', 'sealed')", name=op.f("ck_flex_imports_year_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_flex_imports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flex_imports")),
        sa.UniqueConstraint("organization_id", "xml_hash", name="uq_flex_imports_org_xml_hash"),
    )
    op.create_index(
        op.f("ix_flex_imports_organization_id"), "flex_imports", ["organization_id"], unique=False
    )
    op.create_table(
        "ingest_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("job_kind", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("items_processed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "job_kind IN ('flex', 'trm', 'manual_refresh', 'manual_upload', 'setup_initial')",
            name=op.f("ck_ingest_log_job_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'failed')", name=op.f("ck_ingest_log_status")
        ),
        sa.CheckConstraint(
            "trigger IN ('cron', 'manual', 'wizard')", name=op.f("ck_ingest_log_trigger")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ingest_log_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_log")),
    )
    op.create_index(
        "ix_ingest_log_org_started_at",
        "ingest_log",
        ["organization_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_log_organization_id"), "ingest_log", ["organization_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member')", name=op.f("ck_memberships_role")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "organization_id", name=op.f("pk_memberships")),
        comment="User<->org con rol. Identidad; sin org-RLS (se lee para resolver contexto).",
    )
    op.create_table(
        "parties",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("tax_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_parties_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_parties_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parties")),
        comment="Persona fiscal (contribuyente). Duena de cuentas via participations. Separada de User: puede no tener login (conyuge, cliente del estudio). Org-scoped (organization_id, RLS).",
    )
    op.create_index(
        op.f("ix_parties_organization_id"), "parties", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_parties_user_id"), "parties", ["user_id"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "marginal_rate",
            sa.Numeric(precision=5, scale=4),
            server_default="0.3900",
            nullable=False,
        ),
        sa.Column(
            "timezone", sa.String(length=64), server_default="America/Bogota", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    op.create_table(
        "access_grants",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("grantor_party_id", sa.BigInteger(), nullable=False),
        sa.Column("grantee_organization_id", sa.BigInteger(), nullable=True),
        sa.Column("grantee_user_id", sa.BigInteger(), nullable=True),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(), server_default=sa.text("'read_only'"), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('read_only')", name=op.f("ck_access_grants_role")),
        sa.CheckConstraint(
            "(grantee_organization_id IS NOT NULL) <> (grantee_user_id IS NOT NULL)",
            name=op.f("ck_access_grants_grantee_arc"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_access_grants_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["grantee_organization_id"],
            ["organizations.id"],
            name=op.f("fk_access_grants_grantee_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["grantee_user_id"],
            ["users.id"],
            name=op.f("fk_access_grants_grantee_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["grantor_party_id"],
            ["parties.id"],
            name=op.f("fk_access_grants_grantor_party_id_parties"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_access_grants_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_grants")),
        comment="Grant cross-org party-scoped. RLS especial (grantor-org OR grantee).",
    )
    op.create_index(
        op.f("ix_access_grants_grantee_organization_id"),
        "access_grants",
        ["grantee_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_grants_grantee_user_id"), "access_grants", ["grantee_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_access_grants_grantor_party_id"),
        "access_grants",
        ["grantor_party_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_grants_organization_id"), "access_grants", ["organization_id"], unique=False
    )
    op.create_table(
        "cash_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_cash_transactions_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_cash_transactions_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_cash_transactions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_transactions")),
        sa.UniqueConstraint(
            "organization_id", "transaction_id", name="uq_cash_transactions_org_transaction_id"
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
    )
    op.create_index(op.f("ix_cash_transactions_date"), "cash_transactions", ["date"], unique=False)
    op.create_index(
        op.f("ix_cash_transactions_flex_import_id"),
        "cash_transactions",
        ["flex_import_id"],
        unique=False,
    )
    op.create_table(
        "change_in_dividend_accruals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("conid", sa.String(), nullable=True),
        sa.Column("isin", sa.String(), nullable=True),
        sa.Column("issuer_country", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("pay_date", sa.Date(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("accrual_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("gross_rate_per_share", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("gross_amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tax_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fee_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("net_amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("action_id", sa.String(), nullable=True),
        sa.Column("asset_category", sa.String(), nullable=True),
        sa.Column("sub_category", sa.String(), nullable=True),
        sa.Column("level_of_detail", sa.String(), nullable=True),
        sa.Column("code", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "raw_attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_change_in_dividend_accruals_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_change_in_dividend_accruals_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_change_in_dividend_accruals_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_in_dividend_accruals")),
        sa.UniqueConstraint(
            "account_id",
            "conid",
            "ex_date",
            "pay_date",
            "accrual_date",
            "report_date",
            "action_id",
            "code",
            name="uq_change_in_dividend_accruals_natural_key",
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_change_in_dividend_accruals_natural_key); sin transaction_id.",
    )
    op.create_index(
        op.f("ix_change_in_dividend_accruals_account_id_symbol"),
        "change_in_dividend_accruals",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_in_dividend_accruals_flex_import_id"),
        "change_in_dividend_accruals",
        ["flex_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_in_dividend_accruals_organization_id"),
        "change_in_dividend_accruals",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_in_dividend_accruals_report_date"),
        "change_in_dividend_accruals",
        ["report_date"],
        unique=False,
    )
    op.create_table(
        "flex_import_accounts",
        sa.Column("flex_import_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_flex_import_accounts_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_flex_import_accounts_flex_import_id_flex_imports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_flex_import_accounts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "flex_import_id", "account_id", name=op.f("pk_flex_import_accounts")
        ),
        comment="Procedencia cuenta<->import: cada cuenta observada en un FlexImport (incluidas las AccountInformation-only sin hechos). Org-scoped (RLS). Hecho de primera clase: que cuentas trajo el import de un org. El aislamiento cross-tenant lo da RLS por organization_id; esta tabla sirve al wizard para scopear que cuentas reclama un org via sus imports.",
    )
    op.create_index(
        op.f("ix_flex_import_accounts_organization_id"),
        "flex_import_accounts",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "open_dividend_accruals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("conid", sa.String(), nullable=True),
        sa.Column("isin", sa.String(), nullable=True),
        sa.Column("issuer_country", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("pay_date", sa.Date(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("gross_rate_per_share", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("gross_amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tax_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fee_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("net_amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("action_id", sa.String(), nullable=True),
        sa.Column("asset_category", sa.String(), nullable=True),
        sa.Column("sub_category", sa.String(), nullable=True),
        sa.Column("code", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "raw_attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_open_dividend_accruals_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_open_dividend_accruals_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_open_dividend_accruals_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_open_dividend_accruals")),
        sa.UniqueConstraint(
            "account_id",
            "conid",
            "ex_date",
            "pay_date",
            "report_date",
            "action_id",
            "code",
            name="uq_open_dividend_accruals_natural_key",
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_open_dividend_accruals_natural_key); sin transaction_id.",
    )
    op.create_index(
        op.f("ix_open_dividend_accruals_account_id_symbol"),
        "open_dividend_accruals",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_dividend_accruals_flex_import_id"),
        "open_dividend_accruals",
        ["flex_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_dividend_accruals_organization_id"),
        "open_dividend_accruals",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_dividend_accruals_report_date"),
        "open_dividend_accruals",
        ["report_date"],
        unique=False,
    )
    op.create_table(
        "open_position_lots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cost_basis_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("mark_price_usd", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("mark_value_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("originating_transaction_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_open_position_lots_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_open_position_lots_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_open_position_lots_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_open_position_lots")),
        sa.UniqueConstraint(
            "account_id",
            "symbol",
            "open_date",
            "snapshot_date",
            "originating_transaction_id",
            name="uq_open_position_lots_natural_key",
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_open_position_lots_natural_key); no hay transaction_id global, sí originating_transaction_id como discriminador.",
    )
    op.create_index(
        op.f("ix_open_position_lots_account_id_symbol"),
        "open_position_lots",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_position_lots_flex_import_id"),
        "open_position_lots",
        ["flex_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_position_lots_organization_id"),
        "open_position_lots",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "participations",
        sa.Column("party_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("pct", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.CheckConstraint("pct >= 0 AND pct <= 1", name=op.f("ck_participations_pct_range")),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_participations_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_participations_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_participations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["parties.id"],
            name=op.f("fk_participations_party_id_parties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "party_id", "account_id", "valid_from", name=op.f("pk_participations")
        ),
        comment="Propiedad fiscal: Party posee Account con pct (SCD-2). Org-scoped.",
    )
    op.create_index(
        op.f("ix_participations_organization_id"),
        "participations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("settle_date", sa.Date(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("proceeds_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("commission_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("open_close", sa.String(), nullable=True),
        sa.Column("buy_sell", sa.String(), nullable=False),
        sa.Column(
            "raw_attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("buy_sell IN ('BUY', 'SELL')", name=op.f("ck_trades_buy_sell")),
        sa.CheckConstraint(
            "open_close IS NULL OR open_close IN ('O', 'C')", name=op.f("ck_trades_open_close")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_trades_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_trades_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_trades_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint(
            "organization_id", "transaction_id", name="uq_trades_org_transaction_id"
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
    )
    op.create_index(
        op.f("ix_trades_account_id_symbol"), "trades", ["account_id", "symbol"], unique=False
    )
    op.create_index(op.f("ix_trades_flex_import_id"), "trades", ["flex_import_id"], unique=False)
    op.create_index(op.f("ix_trades_trade_date"), "trades", ["trade_date"], unique=False)
    op.create_table(
        "transfers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("src_account_id", sa.BigInteger(), nullable=True),
        sa.Column("src_counterparty_id", sa.BigInteger(), nullable=True),
        sa.Column("dst_account_id", sa.BigInteger(), nullable=True),
        sa.Column("dst_counterparty_id", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("transfer_type", sa.String(), nullable=False),
        sa.CheckConstraint("direction IN ('IN', 'OUT')", name=op.f("ck_transfers_direction")),
        sa.CheckConstraint(
            "(dst_account_id IS NOT NULL) <> (dst_counterparty_id IS NOT NULL)",
            name=op.f("ck_transfers_dst_arc"),
        ),
        sa.CheckConstraint(
            "(src_account_id IS NOT NULL) <> (src_counterparty_id IS NOT NULL)",
            name=op.f("ck_transfers_src_arc"),
        ),
        sa.ForeignKeyConstraint(
            ["dst_account_id"],
            ["accounts.id"],
            name=op.f("fk_transfers_dst_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dst_counterparty_id"],
            ["counterparties.id"],
            name=op.f("fk_transfers_dst_counterparty_id_counterparties"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_transfers_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_transfers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["src_account_id"],
            ["accounts.id"],
            name=op.f("fk_transfers_src_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["src_counterparty_id"],
            ["counterparties.id"],
            name=op.f("fk_transfers_src_counterparty_id_counterparties"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfers")),
        sa.UniqueConstraint(
            "organization_id", "transaction_id", name="uq_transfers_org_transaction_id"
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
    )
    op.create_index(
        op.f("ix_transfers_dst_account_id"), "transfers", ["dst_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_dst_counterparty_id"), "transfers", ["dst_counterparty_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_flex_import_id"), "transfers", ["flex_import_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_src_account_id"), "transfers", ["src_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_src_counterparty_id"), "transfers", ["src_counterparty_id"], unique=False
    )
    op.create_table(
        "closed_lots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column(
            "close_datetime",
            sa.DateTime(),
            nullable=False,
            comment="Naive POR DISEÑO (D3 sp1-db-hardening): IBKR emite 'YYYYMMDD;HHMMSS' sin timezone (exchange-local); timestamptz inventaría una zona. La regla 730d (Art. 300 ET) opera a granularidad de día sobre close_date.",
        ),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cost_basis_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("proceeds_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fifo_pnl_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("source_trade_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_closed_lots_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_closed_lots_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_closed_lots_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_trade_id"], ["trades.id"], name=op.f("fk_closed_lots_source_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_closed_lots")),
        sa.UniqueConstraint(
            "organization_id",
            "transaction_id",
            "close_datetime",
            "qty",
            "fifo_pnl_usd",
            name="uq_closed_lots_natural_key",
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_closed_lots_natural_key); transaction_id NO es único ni global ni per-org — múltiples ejecuciones de cierre lo comparten (amendment A3); la key es per-tenant (multi-home, spec 2026-06-10).",
    )
    op.create_index(
        op.f("ix_closed_lots_account_id_symbol"),
        "closed_lots",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_closed_lots_flex_import_id"), "closed_lots", ["flex_import_id"], unique=False
    )
    op.create_index(
        op.f("ix_closed_lots_source_trade_id"), "closed_lots", ["source_trade_id"], unique=False
    )
    # ### end Alembic commands ###

    # =======================================================================
    # HAND-WRITTEN SECTIONS (frozen inline — autogenerate cannot emit these).
    # Migrations run as the DB owner (the migrate one-shot container), which is
    # exempt from RLS even under FORCE — so creating the role + policies + the
    # SECURITY DEFINER function all run with the necessary privilege here.
    # =======================================================================

    # --- (1) apscheduler_jobs (runtime table; app_rls has no CREATE) --------
    # Frozen VERBATIM from the old 7fdaf6528762. IF NOT EXISTS is load-bearing
    # (dirty-volume safe): APScheduler's SQLAlchemyJobStore lazily create_all()s
    # this exact table at runtime; a volume that ran a pre-split app already has
    # it. The schema is APScheduler-owned + frozen by the APScheduler==3.11.* pin
    # (no third writer), so IF NOT EXISTS cannot mask meaningful drift. Not in
    # Base.metadata -> the drift test ignores it; test_tier1_baseline asserts it.
    op.execute(
        "CREATE TABLE IF NOT EXISTS apscheduler_jobs ("
        "id VARCHAR(191) NOT NULL PRIMARY KEY, "
        "next_run_time DOUBLE PRECISION, "
        "job_state BYTEA NOT NULL)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_apscheduler_jobs_next_run_time "
        "ON apscheduler_jobs (next_run_time)"
    )

    # --- (2) app_rls role + grants -----------------------------------------
    # The non-superuser, non-owner login role the long-running app connects as,
    # so RLS (with FORCE) actually applies in runtime. Frozen from the output of
    # db/rls.py::app_role_grants_sql(); the password is the only runtime value,
    # read from env via _app_rls_password() (no hardcoded credential in source).
    op.execute(
        f"DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='{_APP_ROLE}') "
        f"THEN CREATE ROLE {_APP_ROLE} LOGIN PASSWORD '{_app_rls_password()}'; END IF; END $$"
    )
    op.execute(f"GRANT USAGE ON SCHEMA public TO {_APP_ROLE}")
    op.execute(
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {_APP_ROLE}"
    )
    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {_APP_ROLE}")
    op.execute(
        f"ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {_APP_ROLE}"
    )
    # apscheduler_jobs was created above without going through ALTER DEFAULT
    # PRIVILEGES timing guarantees; grant DML explicitly (idempotent, frozen from
    # 7fdaf6528762) so the running app can read/write job rows.
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON apscheduler_jobs TO {_APP_ROLE}")

    # --- (3) standard org-isolation RLS policy on every org-scoped table ----
    # Frozen from db/rls.py::standard_policy_sql(). ENABLE + FORCE (so even the
    # table owner is subject) + a single policy keyed on app.current_org.
    for table in _ORG_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY org_isolation ON {table}\n"
            f"            USING (organization_id = {_CURRENT_ORG})\n"
            f"            WITH CHECK (organization_id = {_CURRENT_ORG})"
        )

    # --- (4) special grant_visibility policy on access_grants ---------------
    # Frozen from db/rls.py::access_grants_policy_sql(). A grant is visible to the
    # grantor's org OR the grantee (org or user) — cross-org by design; writes are
    # still confined to the current org.
    op.execute("ALTER TABLE access_grants ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE access_grants FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY grant_visibility ON access_grants\n"
        "            USING (\n"
        f"              organization_id = {_CURRENT_ORG}\n"
        f"              OR grantee_organization_id = {_CURRENT_ORG}\n"
        f"              OR grantee_user_id = {_CURRENT_USER}\n"
        "            )\n"
        f"            WITH CHECK (organization_id = {_CURRENT_ORG})"
    )

    # --- (5) system_credentialed_org_ids() SECURITY DEFINER function --------
    # Frozen from db/rls.py::system_enum_function_sql() — body reads
    # flex_credentials TODAY (a later W1 task repoints it at connections).
    # SECURITY DEFINER (owner is the migration superuser, RLS-exempt) so the
    # Flex cron can enumerate credentialed orgs (a cross-tenant control-plane
    # read that would default-deny to 0 rows as app_rls). SET search_path pins
    # name resolution (anti-hijack); REVOKE FROM PUBLIC + GRANT TO app_rls is
    # least privilege. Not in Base.metadata -> drift test ignores it.
    op.execute(
        "CREATE OR REPLACE FUNCTION system_credentialed_org_ids() "
        "RETURNS SETOF bigint LANGUAGE sql STABLE SECURITY DEFINER "
        "SET search_path = pg_catalog, public AS $$ "
        "SELECT DISTINCT organization_id FROM flex_credentials $$"
    )
    op.execute("REVOKE EXECUTE ON FUNCTION system_credentialed_org_ids() FROM PUBLIC")
    op.execute(f"GRANT EXECUTE ON FUNCTION system_credentialed_org_ids() TO {_APP_ROLE}")


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the hand-written objects first (mirrors the old chain's downgrades:
    # the function from a1f2c3d4e5b6, apscheduler_jobs from 7fdaf6528762). The
    # RLS policies are dropped implicitly with their tables below; the role is
    # dropped last (after its grants are gone with the tables).
    op.execute("DROP FUNCTION IF EXISTS system_credentialed_org_ids()")
    op.execute("DROP INDEX IF EXISTS ix_apscheduler_jobs_next_run_time")
    op.execute("DROP TABLE IF EXISTS apscheduler_jobs")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_closed_lots_source_trade_id"), table_name="closed_lots")
    op.drop_index(op.f("ix_closed_lots_flex_import_id"), table_name="closed_lots")
    op.drop_index(op.f("ix_closed_lots_account_id_symbol"), table_name="closed_lots")
    op.drop_table("closed_lots")
    op.drop_index(op.f("ix_transfers_src_counterparty_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_src_account_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_flex_import_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_dst_counterparty_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_dst_account_id"), table_name="transfers")
    op.drop_table("transfers")
    op.drop_index(op.f("ix_trades_trade_date"), table_name="trades")
    op.drop_index(op.f("ix_trades_flex_import_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_account_id_symbol"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_participations_organization_id"), table_name="participations")
    op.drop_table("participations")
    op.drop_index(op.f("ix_open_position_lots_organization_id"), table_name="open_position_lots")
    op.drop_index(op.f("ix_open_position_lots_flex_import_id"), table_name="open_position_lots")
    op.drop_index(op.f("ix_open_position_lots_account_id_symbol"), table_name="open_position_lots")
    op.drop_table("open_position_lots")
    op.drop_index(
        op.f("ix_open_dividend_accruals_report_date"), table_name="open_dividend_accruals"
    )
    op.drop_index(
        op.f("ix_open_dividend_accruals_organization_id"), table_name="open_dividend_accruals"
    )
    op.drop_index(
        op.f("ix_open_dividend_accruals_flex_import_id"), table_name="open_dividend_accruals"
    )
    op.drop_index(
        op.f("ix_open_dividend_accruals_account_id_symbol"), table_name="open_dividend_accruals"
    )
    op.drop_table("open_dividend_accruals")
    op.drop_index(
        op.f("ix_flex_import_accounts_organization_id"), table_name="flex_import_accounts"
    )
    op.drop_table("flex_import_accounts")
    op.drop_index(
        op.f("ix_change_in_dividend_accruals_report_date"), table_name="change_in_dividend_accruals"
    )
    op.drop_index(
        op.f("ix_change_in_dividend_accruals_organization_id"),
        table_name="change_in_dividend_accruals",
    )
    op.drop_index(
        op.f("ix_change_in_dividend_accruals_flex_import_id"),
        table_name="change_in_dividend_accruals",
    )
    op.drop_index(
        op.f("ix_change_in_dividend_accruals_account_id_symbol"),
        table_name="change_in_dividend_accruals",
    )
    op.drop_table("change_in_dividend_accruals")
    op.drop_index(op.f("ix_cash_transactions_flex_import_id"), table_name="cash_transactions")
    op.drop_index(op.f("ix_cash_transactions_date"), table_name="cash_transactions")
    op.drop_table("cash_transactions")
    op.drop_index(op.f("ix_access_grants_organization_id"), table_name="access_grants")
    op.drop_index(op.f("ix_access_grants_grantor_party_id"), table_name="access_grants")
    op.drop_index(op.f("ix_access_grants_grantee_user_id"), table_name="access_grants")
    op.drop_index(op.f("ix_access_grants_grantee_organization_id"), table_name="access_grants")
    op.drop_table("access_grants")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_parties_user_id"), table_name="parties")
    op.drop_index(op.f("ix_parties_organization_id"), table_name="parties")
    op.drop_table("parties")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_ingest_log_organization_id"), table_name="ingest_log")
    op.drop_index("ix_ingest_log_org_started_at", table_name="ingest_log")
    op.drop_table("ingest_log")
    op.drop_index(op.f("ix_flex_imports_organization_id"), table_name="flex_imports")
    op.drop_table("flex_imports")
    op.drop_index(op.f("ix_flex_credentials_organization_id"), table_name="flex_credentials")
    op.drop_table("flex_credentials")
    op.drop_index(op.f("ix_counterparties_organization_id"), table_name="counterparties")
    op.drop_table("counterparties")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("trm_imports")
    op.drop_index(op.f("ix_trm_days_date"), table_name="trm_days")
    op.drop_table("trm_days")
    op.drop_table("organizations")
    # ### end Alembic commands ###

    # Role last: its grants are gone once the tables are dropped. This is a wipe
    # baseline, so downgrade fidelity is low-priority (frozen from 05943d9efcdb).
    op.execute(f"DROP ROLE IF EXISTS {_APP_ROLE}")
