"""phase2_identity: accounts + participations + flex_credentials + users.setup_*

Revision ID: aa6d6903b8f7
Revises: d24cab8c4630
Create Date: 2026-05-24 13:30:50.427416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa6d6903b8f7'
down_revision: Union[str, Sequence[str], None] = 'd24cab8c4630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ibkr_account_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ibkr_account_id')
    )
    op.create_table('flex_credentials',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('ytd_query_id', sa.String(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('participations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.CheckConstraint('pct >= 0 AND pct <= 1', name='ck_participations_pct_range'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_participations_valid_range'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'account_id', 'valid_from')
    )
    op.add_column('users', sa.Column('setup_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('setup_progress', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'setup_progress')
    op.drop_column('users', 'setup_completed_at')
    op.drop_table('participations')
    op.drop_table('flex_credentials')
    op.drop_table('accounts')
    # ### end Alembic commands ###
