"""phase2_ingest_log

Revision ID: b2073418f290
Revises: cc1e2833d609
Create Date: 2026-05-24 13:55:46.633418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2073418f290"
down_revision: Union[str, Sequence[str], None] = "cc1e2833d609"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_kind", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("items_processed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "job_kind IN ('flex', 'trm', 'manual_refresh', 'manual_upload', 'setup_initial')",
            name="ingest_log_job_kind_check",
        ),
        sa.CheckConstraint("status IN ('running', 'ok', 'failed')", name="ingest_log_status_check"),
        sa.CheckConstraint(
            "trigger IN ('cron', 'manual', 'wizard')", name="ingest_log_trigger_check"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ingest_log_user_started_idx",
        "ingest_log",
        ["user_id", sa.text("started_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ingest_log_user_started_idx", table_name="ingest_log")
    op.drop_table("ingest_log")
    # ### end Alembic commands ###
