"""baseline schema

Revision ID: cbeaac94933d
Revises:
Create Date: 2026-06-02 14:52:28.597190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cbeaac94933d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ibkr_account_id", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("ibkr_account_id", name=op.f("uq_accounts_ibkr_account_id")),
        comment="Identidad COMPARTIDA. Una fila por cuenta IBKR; sin user_id a propósito — la propiedad se modela en participations (la conjunta es 50/50). ibkr_account_id UNIQUE global es correcto.",
    )
    op.create_table(
        "counterparties",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("source_label", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_counterparties")),
        sa.UniqueConstraint("external_id", name=op.f("uq_counterparties_external_id")),
        comment="Identidad compartida externa (espeja accounts). Sin user_id.",
    )
    op.create_table(
        "trm_days",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value_cop", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("vigencia_desde", sa.Date(), nullable=False),
        sa.Column("vigencia_hasta", sa.Date(), nullable=False),
        sa.Column(
            "source",
            sa.String(),
            server_default=sa.text("'dian_socrata_ceyp_9c7c'"),
            nullable=False,
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_trm_days")),
        comment="1 row por día calendario, expandido desde vigencia_desde..vigencia_hasta",
    )
    op.create_index(op.f("ix_trm_days_date"), "trm_days", ["date"], unique=False)
    op.create_table(
        "trm_imports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date_range_from", sa.Date(), nullable=False),
        sa.Column("date_range_to", sa.Date(), nullable=False),
        sa.Column("n_rows_api", sa.Integer(), nullable=False),
        sa.Column("n_days_expanded", sa.Integer(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trm_imports")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("setup_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "setup_progress",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_ingest_trigger_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "data_access_grants",
        sa.Column("grantor_user_id", sa.BigInteger(), nullable=False),
        sa.Column("grantee_user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(), server_default=sa.text("'read_only'"), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('read_only')", name=op.f("ck_data_access_grants_role")),
        sa.CheckConstraint(
            "grantor_user_id <> grantee_user_id", name=op.f("ck_data_access_grants_no_self")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_data_access_grants_valid_range"),
        ),
        sa.ForeignKeyConstraint(
            ["grantee_user_id"],
            ["users.id"],
            name=op.f("fk_data_access_grants_grantee_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["grantor_user_id"],
            ["users.id"],
            name=op.f("fk_data_access_grants_grantor_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "grantor_user_id", "grantee_user_id", "valid_from", name=op.f("pk_data_access_grants")
        ),
        comment="Delegación de lectura read-only: grantor habilita a grantee a leer sus datos vía las participations del grantor. Separada de participations: poder-leer no es poseer.",
    )
    op.create_table(
        "flex_credentials",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("ytd_query_id", sa.String(), nullable=False),
        sa.Column(
            "last_rotated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_flex_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_flex_credentials")),
    )
    op.create_table(
        "flex_imports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("anyo", sa.Integer(), nullable=False),
        sa.Column("xml_hash", sa.String(), nullable=False),
        sa.Column("xml_size_bytes", sa.Integer(), nullable=False),
        sa.Column("xml_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("period_covered_from", sa.Date(), nullable=False),
        sa.Column("period_covered_to", sa.Date(), nullable=False),
        sa.Column("year_status", sa.String(), server_default=sa.text("'rolling'"), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("n_observed_trades", sa.Integer(), nullable=True),
        sa.Column("n_observed_lots_closed", sa.Integer(), nullable=True),
        sa.Column("n_observed_open_lots", sa.Integer(), nullable=True),
        sa.Column("n_observed_cash_tx", sa.Integer(), nullable=True),
        sa.Column("n_observed_dividends", sa.Integer(), nullable=True),
        sa.Column("n_observed_transfers", sa.Integer(), nullable=True),
        sa.Column("n_new_trades", sa.Integer(), nullable=True),
        sa.Column("n_new_lots_closed", sa.Integer(), nullable=True),
        sa.Column("n_new_open_lots", sa.Integer(), nullable=True),
        sa.Column("n_new_cash_tx", sa.Integer(), nullable=True),
        sa.Column("n_new_dividends", sa.Integer(), nullable=True),
        sa.Column("n_new_transfers", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("poison_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "source IN ('web_service', 'manual_upload')", name=op.f("ck_flex_imports_source")
        ),
        sa.CheckConstraint("status IN ('ok', 'poison')", name=op.f("ck_flex_imports_status")),
        sa.CheckConstraint(
            "year_status IN ('rolling', 'sealed')", name=op.f("ck_flex_imports_year_status")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_flex_imports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flex_imports")),
        sa.UniqueConstraint("user_id", "xml_hash", name=op.f("uq_flex_imports_user_id_xml_hash")),
    )
    op.create_table(
        "ingest_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_kind", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("items_processed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "job_kind IN ('flex', 'trm', 'manual_refresh', 'manual_upload', 'setup_initial')",
            name=op.f("ck_ingest_log_job_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'failed')", name=op.f("ck_ingest_log_status")
        ),
        sa.CheckConstraint(
            "trigger IN ('cron', 'manual', 'wizard')", name=op.f("ck_ingest_log_trigger")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ingest_log_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_log")),
    )
    op.create_index(
        "ix_ingest_log_user_id_started_at",
        "ingest_log",
        ["user_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "participations",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("pct", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.CheckConstraint("pct >= 0 AND pct <= 1", name=op.f("ck_participations_pct_range")),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_participations_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_participations_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_participations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "account_id", "valid_from", name=op.f("pk_participations")
        ),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "marginal_rate",
            sa.Numeric(precision=5, scale=4),
            server_default="0.3900",
            nullable=False,
        ),
        sa.Column(
            "timezone", sa.String(length=64), server_default="America/Bogota", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    op.create_table(
        "cash_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_cash_transactions_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_cash_transactions_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_transactions")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_cash_transactions_transaction_id")),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
    )
    op.create_index(op.f("ix_cash_transactions_date"), "cash_transactions", ["date"], unique=False)
    op.create_table(
        "change_in_dividend_accruals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("conid", sa.String(), nullable=True),
        sa.Column("isin", sa.String(), nullable=True),
        sa.Column("issuer_country", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("pay_date", sa.Date(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("accrual_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("gross_rate_per_share", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("gross_amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tax_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fee_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("net_amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("action_id", sa.String(), nullable=True),
        sa.Column("asset_category", sa.String(), nullable=True),
        sa.Column("sub_category", sa.String(), nullable=True),
        sa.Column("level_of_detail", sa.String(), nullable=True),
        sa.Column("code", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "raw_attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_change_in_dividend_accruals_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_change_in_dividend_accruals_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_in_dividend_accruals")),
        sa.UniqueConstraint(
            "account_id",
            "conid",
            "ex_date",
            "pay_date",
            "accrual_date",
            "report_date",
            "action_id",
            "code",
            name="uq_change_in_dividend_accruals_natural_key",
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_change_in_dividend_accruals_natural_key); sin transaction_id.",
    )
    op.create_index(
        op.f("ix_change_in_dividend_accruals_account_id_symbol"),
        "change_in_dividend_accruals",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_in_dividend_accruals_report_date"),
        "change_in_dividend_accruals",
        ["report_date"],
        unique=False,
    )
    op.create_table(
        "open_dividend_accruals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("conid", sa.String(), nullable=True),
        sa.Column("isin", sa.String(), nullable=True),
        sa.Column("issuer_country", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("pay_date", sa.Date(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("gross_rate_per_share", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("gross_amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tax_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fee_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("net_amount_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("action_id", sa.String(), nullable=True),
        sa.Column("asset_category", sa.String(), nullable=True),
        sa.Column("sub_category", sa.String(), nullable=True),
        sa.Column("code", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "raw_attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_open_dividend_accruals_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_open_dividend_accruals_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_open_dividend_accruals")),
        sa.UniqueConstraint(
            "account_id",
            "conid",
            "ex_date",
            "pay_date",
            "report_date",
            "action_id",
            "code",
            name="uq_open_dividend_accruals_natural_key",
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_open_dividend_accruals_natural_key); sin transaction_id.",
    )
    op.create_index(
        op.f("ix_open_dividend_accruals_account_id_symbol"),
        "open_dividend_accruals",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_dividend_accruals_report_date"),
        "open_dividend_accruals",
        ["report_date"],
        unique=False,
    )
    op.create_table(
        "open_position_lots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cost_basis_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("mark_price_usd", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("mark_value_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("originating_transaction_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_open_position_lots_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_open_position_lots_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_open_position_lots")),
        sa.UniqueConstraint(
            "account_id",
            "symbol",
            "open_date",
            "snapshot_date",
            "originating_transaction_id",
            name="uq_open_position_lots_natural_key",
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_open_position_lots_natural_key); no hay transaction_id global, sí originating_transaction_id como discriminador.",
    )
    op.create_index(
        op.f("ix_open_position_lots_account_id_symbol"),
        "open_position_lots",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("settle_date", sa.Date(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("proceeds_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("commission_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("open_close", sa.String(), nullable=True),
        sa.Column("buy_sell", sa.String(), nullable=False),
        sa.Column(
            "raw_attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("buy_sell IN ('BUY', 'SELL')", name=op.f("ck_trades_buy_sell")),
        sa.CheckConstraint(
            "open_close IS NULL OR open_close IN ('O', 'C')", name=op.f("ck_trades_open_close")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_trades_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_trades_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_trades_transaction_id")),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
    )
    op.create_index(
        op.f("ix_trades_account_id_symbol"), "trades", ["account_id", "symbol"], unique=False
    )
    op.create_index(op.f("ix_trades_trade_date"), "trades", ["trade_date"], unique=False)
    op.create_table(
        "transfers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("src_account_id", sa.BigInteger(), nullable=True),
        sa.Column("src_counterparty_id", sa.BigInteger(), nullable=True),
        sa.Column("dst_account_id", sa.BigInteger(), nullable=True),
        sa.Column("dst_counterparty_id", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("transfer_type", sa.String(), nullable=False),
        sa.CheckConstraint("direction IN ('IN', 'OUT')", name=op.f("ck_transfers_direction")),
        sa.CheckConstraint(
            "(dst_account_id IS NOT NULL) <> (dst_counterparty_id IS NOT NULL)",
            name=op.f("ck_transfers_dst_arc"),
        ),
        sa.CheckConstraint(
            "(src_account_id IS NOT NULL) <> (src_counterparty_id IS NOT NULL)",
            name=op.f("ck_transfers_src_arc"),
        ),
        sa.ForeignKeyConstraint(
            ["dst_account_id"], ["accounts.id"], name=op.f("fk_transfers_dst_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["dst_counterparty_id"],
            ["counterparties.id"],
            name=op.f("fk_transfers_dst_counterparty_id_counterparties"),
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_transfers_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["src_account_id"], ["accounts.id"], name=op.f("fk_transfers_src_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["src_counterparty_id"],
            ["counterparties.id"],
            name=op.f("fk_transfers_src_counterparty_id_counterparties"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfers")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_transfers_transaction_id")),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
    )
    op.create_table(
        "closed_lots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column("close_datetime", sa.DateTime(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cost_basis_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("proceeds_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fifo_pnl_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("source_trade_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_closed_lots_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["flex_import_id"],
            ["flex_imports.id"],
            name=op.f("fk_closed_lots_flex_import_id_flex_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_trade_id"], ["trades.id"], name=op.f("fk_closed_lots_source_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_closed_lots")),
        sa.UniqueConstraint(
            "transaction_id",
            "close_datetime",
            "qty",
            "fifo_pnl_usd",
            name="uq_closed_lots_natural_key",
        ),
        comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_closed_lots_natural_key); transaction_id NO es único global — múltiples ejecuciones de cierre lo comparten (amendment A3).",
    )
    op.create_index(
        op.f("ix_closed_lots_account_id_symbol"),
        "closed_lots",
        ["account_id", "symbol"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_closed_lots_account_id_symbol"), table_name="closed_lots")
    op.drop_table("closed_lots")
    op.drop_table("transfers")
    op.drop_index(op.f("ix_trades_trade_date"), table_name="trades")
    op.drop_index(op.f("ix_trades_account_id_symbol"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_open_position_lots_account_id_symbol"), table_name="open_position_lots")
    op.drop_table("open_position_lots")
    op.drop_index(
        op.f("ix_open_dividend_accruals_report_date"), table_name="open_dividend_accruals"
    )
    op.drop_index(
        op.f("ix_open_dividend_accruals_account_id_symbol"), table_name="open_dividend_accruals"
    )
    op.drop_table("open_dividend_accruals")
    op.drop_index(
        op.f("ix_change_in_dividend_accruals_report_date"), table_name="change_in_dividend_accruals"
    )
    op.drop_index(
        op.f("ix_change_in_dividend_accruals_account_id_symbol"),
        table_name="change_in_dividend_accruals",
    )
    op.drop_table("change_in_dividend_accruals")
    op.drop_index(op.f("ix_cash_transactions_date"), table_name="cash_transactions")
    op.drop_table("cash_transactions")
    op.drop_table("user_settings")
    op.drop_table("participations")
    op.drop_index("ix_ingest_log_user_id_started_at", table_name="ingest_log")
    op.drop_table("ingest_log")
    op.drop_table("flex_imports")
    op.drop_table("flex_credentials")
    op.drop_table("data_access_grants")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("trm_imports")
    op.drop_index(op.f("ix_trm_days_date"), table_name="trm_days")
    op.drop_table("trm_days")
    op.drop_table("counterparties")
    op.drop_table("accounts")
    # ### end Alembic commands ###
