"""phase2_flex_raw: flex_imports + trades + lots + transfers + cash_transactions

Revision ID: cc1e2833d609
Revises: 708bf9864c1e
Create Date: 2026-05-24 13:49:42.930910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cc1e2833d609"
down_revision: Union[str, Sequence[str], None] = "708bf9864c1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flex_imports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("anyo", sa.Integer(), nullable=False),
        sa.Column("xml_hash", sa.String(), nullable=False),
        sa.Column("xml_size_bytes", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("period_covered_from", sa.Date(), nullable=False),
        sa.Column("period_covered_to", sa.Date(), nullable=False),
        sa.Column("year_status", sa.String(), server_default=sa.text("'rolling'"), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("n_trades", sa.Integer(), nullable=True),
        sa.Column("n_lots_closed", sa.Integer(), nullable=True),
        sa.Column("n_open_lots", sa.Integer(), nullable=True),
        sa.Column("n_cash_tx", sa.Integer(), nullable=True),
        sa.Column("n_dividends", sa.Integer(), nullable=True),
        sa.Column("n_transfers", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.CheckConstraint(
            "source IN ('web_service', 'manual_upload')", name="ck_flex_imports_source"
        ),
        sa.CheckConstraint("status IN ('ok', 'failed')", name="ck_flex_imports_status"),
        sa.CheckConstraint(
            "year_status IN ('rolling', 'sealed')", name="ck_flex_imports_year_status"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("xml_hash"),
    )
    op.create_table(
        "cash_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["flex_import_id"], ["flex_imports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("cash_transactions_date_idx", "cash_transactions", ["date"], unique=False)
    op.create_table(
        "open_position_lots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("cost_basis_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("mark_price_usd", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("mark_value_usd", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["flex_import_id"], ["flex_imports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "open_position_lots_account_symbol_idx",
        "open_position_lots",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("settle_date", sa.Date(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("proceeds_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("commission_usd", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("open_close", sa.String(), nullable=True),
        sa.Column("buy_sell", sa.String(), nullable=False),
        sa.Column(
            "raw_attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("buy_sell IN ('BUY', 'SELL')", name="ck_trades_buy_sell"),
        sa.CheckConstraint(
            "open_close IS NULL OR open_close IN ('O', 'C')", name="ck_trades_open_close"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["flex_import_id"], ["flex_imports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_index("trades_account_symbol_idx", "trades", ["account_id", "symbol"], unique=False)
    op.create_index("trades_trade_date_idx", "trades", ["trade_date"], unique=False)
    op.create_table(
        "transfers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("src_account_id", sa.BigInteger(), nullable=True),
        sa.Column("dst_account_id", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("transfer_type", sa.String(), nullable=False),
        sa.CheckConstraint("direction IN ('IN', 'OUT')", name="ck_transfers_direction"),
        sa.ForeignKeyConstraint(
            ["dst_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["flex_import_id"], ["flex_imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["src_account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "closed_lots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flex_import_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("cost_basis_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("proceeds_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("fifo_pnl_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("source_trade_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["flex_import_id"], ["flex_imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "closed_lots_account_symbol_idx", "closed_lots", ["account_id", "symbol"], unique=False
    )
    op.create_table(
        "transfer_lots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("transfer_id", sa.BigInteger(), nullable=False),
        sa.Column("original_open_date", sa.Date(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("cost_basis_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["transfer_id"], ["transfers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transfer_lots")
    op.drop_index("closed_lots_account_symbol_idx", table_name="closed_lots")
    op.drop_table("closed_lots")
    op.drop_table("transfers")
    op.drop_index("trades_trade_date_idx", table_name="trades")
    op.drop_index("trades_account_symbol_idx", table_name="trades")
    op.drop_table("trades")
    op.drop_index("open_position_lots_account_symbol_idx", table_name="open_position_lots")
    op.drop_table("open_position_lots")
    op.drop_index("cash_transactions_date_idx", table_name="cash_transactions")
    op.drop_table("cash_transactions")
    op.drop_table("flex_imports")
    # ### end Alembic commands ###
