"""add users.last_ingest_trigger_at for rate limit

Revision ID: e39428dc5cd5
Revises: ee936c932d85
Create Date: 2026-05-24 18:10:36.060225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e39428dc5cd5"
down_revision: Union[str, Sequence[str], None] = "ee936c932d85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_ingest_trigger_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_ingest_trigger_at")
    # ### end Alembic commands ###
