"""phase2_widen_precision_for_fifo: widen Numeric(20,2)->(20,4) on USD totals + Numeric(20,6)->(20,8) on quantities

Revision ID: ee936c932d85
Revises: 1ea0a9924a1b
Create Date: 2026-05-24 16:36:13.337816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee936c932d85'
down_revision: Union[str, Sequence[str], None] = '1ea0a9924a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cash_transactions', 'amount_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('change_in_dividend_accruals', 'quantity',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('change_in_dividend_accruals', 'gross_amount_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('change_in_dividend_accruals', 'tax_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('change_in_dividend_accruals', 'fee_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('change_in_dividend_accruals', 'net_amount_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('closed_lots', 'qty',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('closed_lots', 'cost_basis_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('closed_lots', 'proceeds_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('closed_lots', 'fifo_pnl_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('open_dividend_accruals', 'quantity',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('open_dividend_accruals', 'gross_amount_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('open_dividend_accruals', 'tax_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('open_dividend_accruals', 'fee_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('open_dividend_accruals', 'net_amount_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('open_position_lots', 'qty',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('open_position_lots', 'cost_basis_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('open_position_lots', 'mark_value_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('trades', 'qty',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('trades', 'proceeds_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('transfer_lots', 'qty',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('transfer_lots', 'cost_basis_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('transfers', 'qty',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfers', 'qty',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    op.alter_column('transfer_lots', 'cost_basis_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('transfer_lots', 'qty',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    op.alter_column('trades', 'proceeds_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('trades', 'qty',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    op.alter_column('open_position_lots', 'mark_value_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('open_position_lots', 'cost_basis_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('open_position_lots', 'qty',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    op.alter_column('open_dividend_accruals', 'net_amount_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('open_dividend_accruals', 'fee_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('open_dividend_accruals', 'tax_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('open_dividend_accruals', 'gross_amount_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('open_dividend_accruals', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    op.alter_column('closed_lots', 'fifo_pnl_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('closed_lots', 'proceeds_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('closed_lots', 'cost_basis_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('closed_lots', 'qty',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    op.alter_column('change_in_dividend_accruals', 'net_amount_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('change_in_dividend_accruals', 'fee_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('change_in_dividend_accruals', 'tax_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('change_in_dividend_accruals', 'gross_amount_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('change_in_dividend_accruals', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=20, scale=6),
               existing_nullable=False)
    op.alter_column('cash_transactions', 'amount_usd',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
