"""account multihome: per-org uniqueness

Tenancy canónica per-org (patrón Plaid/Sharesight, spec 2026-06-10): la unicidad
de los hechos pasa de GLOBAL a POR TENANT. La misma cuenta broker puede existir
en N orgs, cada org con su copia aislada (RLS).

upgrade():
- accounts: drop uq_accounts_ibkr_account_id (global) -> create
  uq_accounts_org_ibkr_account_id (organization_id, ibkr_account_id).
- trades/cash_transactions/transfers: drop uq_<tabla>_transaction_id (global) ->
  create uq_<tabla>_org_transaction_id (organization_id, transaction_id).
- closed_lots: la natural key gana organization_id al frente (mismo name).
- drop de los 5 indices ix_<tabla>_organization_id redundantes: las composites
  nuevas empiezan en organization_id y cubren el prefijo que usa la política RLS.
- comments de los 5 tablas reescritos a la semántica per-org (M4).

downgrade():
- Recrea los uniques GLOBALES. SOLO es ejecutable si NO hay datos multi-home:
  si dos orgs comparten la misma ibkr_account_id (o transaction_id), recrear el
  unique global FALLA en la constraint. Es el comportamiento correcto — el
  downgrade no puede colapsar dos universos aislados en uno sin perder datos.

apscheduler_jobs es una tabla runtime de APScheduler (no en Base.metadata);
autogenerate la marca como "removed"/"added" — falso positivo removido a mano
(documentado desde Phase 2.9, igual que las migraciones previas).

Revision ID: fd27737af54e
Revises: 544a0b2c362c
Create Date: 2026-06-10 14:15:18.238363

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd27737af54e"
down_revision: Union[str, Sequence[str], None] = "544a0b2c362c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # apscheduler_jobs is a runtime table managed by APScheduler (not in
    # Base.metadata); autogenerate marks it "removed" as a known false positive
    # — excluded here exactly as prior migrations do.
    op.drop_index(op.f("ix_accounts_organization_id"), table_name="accounts")
    op.drop_constraint(op.f("uq_accounts_ibkr_account_id"), "accounts", type_="unique")
    op.create_unique_constraint(
        "uq_accounts_org_ibkr_account_id", "accounts", ["organization_id", "ibkr_account_id"]
    )
    op.create_table_comment(
        "accounts",
        "Multi-home (patrón Plaid, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, una fila por org — universos aislados, el SaaS no verifica exclusividad de propiedad. Dentro de un org sigue siendo identidad compartida: sin user_id, propiedad vía participations (la conjunta es 50/50).",
        existing_comment="Identidad COMPARTIDA. Una fila por cuenta IBKR; sin user_id a propósito — la propiedad se modela en participations (la conjunta es 50/50). ibkr_account_id UNIQUE global es correcto.",
        schema=None,
    )
    op.drop_index(op.f("ix_cash_transactions_organization_id"), table_name="cash_transactions")
    op.drop_constraint(
        op.f("uq_cash_transactions_transaction_id"), "cash_transactions", type_="unique"
    )
    op.create_unique_constraint(
        "uq_cash_transactions_org_transaction_id",
        "cash_transactions",
        ["organization_id", "transaction_id"],
    )
    op.create_table_comment(
        "cash_transactions",
        "Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
        existing_comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
        schema=None,
    )
    op.drop_index(op.f("ix_closed_lots_organization_id"), table_name="closed_lots")
    op.drop_constraint(op.f("uq_closed_lots_natural_key"), "closed_lots", type_="unique")
    op.create_unique_constraint(
        "uq_closed_lots_natural_key",
        "closed_lots",
        ["organization_id", "transaction_id", "close_datetime", "qty", "fifo_pnl_usd"],
    )
    op.create_table_comment(
        "closed_lots",
        "Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_closed_lots_natural_key); transaction_id NO es único ni global ni per-org — múltiples ejecuciones de cierre lo comparten (amendment A3); la key es per-tenant (multi-home, spec 2026-06-10).",
        existing_comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_closed_lots_natural_key); transaction_id NO es único global — múltiples ejecuciones de cierre lo comparten (amendment A3).",
        schema=None,
    )
    op.drop_index(op.f("ix_trades_organization_id"), table_name="trades")
    op.drop_constraint(op.f("uq_trades_transaction_id"), "trades", type_="unique")
    op.create_unique_constraint(
        "uq_trades_org_transaction_id", "trades", ["organization_id", "transaction_id"]
    )
    op.create_table_comment(
        "trades",
        "Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
        existing_comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
        schema=None,
    )
    op.drop_index(op.f("ix_transfers_organization_id"), table_name="transfers")
    op.drop_constraint(op.f("uq_transfers_transaction_id"), "transfers", type_="unique")
    op.create_unique_constraint(
        "uq_transfers_org_transaction_id", "transfers", ["organization_id", "transaction_id"]
    )
    op.create_table_comment(
        "transfers",
        "Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
        existing_comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "transfers",
        "Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
        existing_comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
        schema=None,
    )
    op.drop_constraint("uq_transfers_org_transaction_id", "transfers", type_="unique")
    op.create_unique_constraint(
        op.f("uq_transfers_transaction_id"),
        "transfers",
        ["transaction_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_transfers_organization_id"), "transfers", ["organization_id"], unique=False
    )
    op.create_table_comment(
        "trades",
        "Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
        existing_comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
        schema=None,
    )
    op.drop_constraint("uq_trades_org_transaction_id", "trades", type_="unique")
    op.create_unique_constraint(
        op.f("uq_trades_transaction_id"),
        "trades",
        ["transaction_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_trades_organization_id"), "trades", ["organization_id"], unique=False)
    op.create_table_comment(
        "closed_lots",
        "Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_closed_lots_natural_key); transaction_id NO es único global — múltiples ejecuciones de cierre lo comparten (amendment A3).",
        existing_comment="Account-scoped. Visibilidad vía participations; sin user_id. Identidad por natural key compuesto (uq_closed_lots_natural_key); transaction_id NO es único ni global ni per-org — múltiples ejecuciones de cierre lo comparten (amendment A3); la key es per-tenant (multi-home, spec 2026-06-10).",
        schema=None,
    )
    op.drop_constraint("uq_closed_lots_natural_key", "closed_lots", type_="unique")
    op.create_unique_constraint(
        op.f("uq_closed_lots_natural_key"),
        "closed_lots",
        ["transaction_id", "close_datetime", "qty", "fifo_pnl_usd"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_closed_lots_organization_id"), "closed_lots", ["organization_id"], unique=False
    )
    op.create_table_comment(
        "cash_transactions",
        "Account-scoped. Visibilidad vía participations; sin user_id. transaction_id UNIQUE global correcto — un hecho pertenece a la cuenta, no al usuario.",
        existing_comment="Account-scoped. Visibilidad vía participations; sin user_id. transaction_id único POR TENANT (multi-home, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, cada org tiene su copia de los hechos.",
        schema=None,
    )
    op.drop_constraint(
        "uq_cash_transactions_org_transaction_id", "cash_transactions", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_cash_transactions_transaction_id"),
        "cash_transactions",
        ["transaction_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_cash_transactions_organization_id"),
        "cash_transactions",
        ["organization_id"],
        unique=False,
    )
    op.create_table_comment(
        "accounts",
        "Identidad COMPARTIDA. Una fila por cuenta IBKR; sin user_id a propósito — la propiedad se modela en participations (la conjunta es 50/50). ibkr_account_id UNIQUE global es correcto.",
        existing_comment="Multi-home (patrón Plaid, spec 2026-06-10): la misma cuenta broker puede existir en N orgs, una fila por org — universos aislados, el SaaS no verifica exclusividad de propiedad. Dentro de un org sigue siendo identidad compartida: sin user_id, propiedad vía participations (la conjunta es 50/50).",
        schema=None,
    )
    op.drop_constraint("uq_accounts_org_ibkr_account_id", "accounts", type_="unique")
    op.create_unique_constraint(
        op.f("uq_accounts_ibkr_account_id"),
        "accounts",
        ["ibkr_account_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_accounts_organization_id"), "accounts", ["organization_id"], unique=False
    )
    # apscheduler_jobs intentionally NOT recreated here — it is a runtime table
    # managed by APScheduler (not in Base.metadata), a known autogenerate false
    # positive excluded from the upgrade as well.
    # ### end Alembic commands ###
